apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus-thanos-grafana
  name: grafana-service
spec:
  type: NodePort
  selector:
    name: grafana
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30002