apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus-thanos-grafana
  name: prometheus-service
spec:
  type: NodePort
  selector:
    name: prometheus
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 30001