apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus
  name: prometheus-thanos
spec:
  ports:
  - name: grpc
    port: 10901
    protocol: TCP
    targetPort: 10901
  selector:
    app: prometheus
  type: ClusterIP
