apiVersion: v1
kind: Service
metadata:
  name: thanos-querier
  labels:
    app: thanos-querier
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 10902
    targetPort: 10902
  - name: grpc
    port: 10901
    targetPort: 10901
  selector:
    app: thanos-querier