apiVersion: v1
kind: Service
metadata:
  name: thanos-store-gateway
  labels:
    app: thanos-store-gateway
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 10902
    targetPort: 10902
  - name: grpc
    port: 10901
    targetPort: 10901
  selector:
    app: thanos-store-gateway
