apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus-thanos-grafana
  name: telegraf-service
spec:
  ports:
  - name: tcp
    port: 9273
    protocol: TCP
    targetPort: 9273
  selector:
    name: telegraf
  type: ClusterIP
