apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-querier
  labels:
    app.kubernetes.io/component: poc-thanos-querier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thanos-querier
  template:
    metadata:
      labels:
        app.kubernetes.io/component: poc-thanos-querier
        app: thanos-querier
    spec:
      containers:
      - name: thanos-querier
        image: docker-conveyor.groupondev.com/thanos/thanos:v0.32.0
        args:
        - query
        - --log.level=debug
        - --query.replica-label=replica
        - --endpoint=thanos-store-gateway:10901
        - --endpoint=prometheus-thanos:10901
        ports:
        - name: http
          containerPort: 10902
        - name: grpc
          containerPort: 10901
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
        readinessProbe:
          exec:
            command:
            - ls
            - /
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 3
        livenessProbe:
          exec:
            command:
            - ls
            - /

    